# Generated by Django 4.1.1 on 2023-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0003_profile_lifeline1_postcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correctanswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='logoutTime',
            field=models.IntegerField(null=True),
        ),
    ]
