# Generated by Django 4.1.1 on 2023-05-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0006_chatgptlifeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='correctanswers',
        ),
    ]
