# Generated by Django 4.1.1 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0007_remove_profile_correctanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correctanswers',
            field=models.IntegerField(default=0),
        ),
    ]
