# Generated by Django 4.1.1 on 2023-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0010_alter_profile_focuscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline3_status',
            field=models.BooleanField(default=False),
        ),
    ]
