# Generated by Django 4.1.1 on 2023-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0012_remove_easyquestion_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline2_superstatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifeline2_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifeline3_status',
            field=models.BooleanField(default=True),
        ),
    ]
