# Generated by Django 4.1.1 on 2023-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0013_profile_lifeline2_superstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newlogin',
            field=models.BooleanField(default=False),
        ),
    ]
