# Generated by Django 4.1.1 on 2023-05-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0014_profile_newlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='curr_question',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='focuscount',
        ),
    ]
