# Generated by Django 4.1.1 on 2023-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0016_profile_category_question_is_junior'),
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='minusmrks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='plusmrks',
            field=models.IntegerField(default=10),
        ),
    ]
