# Generated by Django 4.1.1 on 2023-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0020_profile_lifeline3_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cacheAnswer',
            field=models.IntegerField(default=-1),
        ),
    ]
