# Generated by Django 4.0.5 on 2023-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0024_alter_profile_remainingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remainingTime',
            field=models.IntegerField(default=1800),
        ),
    ]
