# Generated by Django 4.0.5 on 2023-05-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0025_alter_profile_remainingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lifelin2_secondattempt',
            new_name='lifeline2_secondattempt',
        ),
    ]
