# Generated by Django 4.1.1 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline2_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline2_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remainingTime',
            field=models.IntegerField(default=1800),
        ),
    ]
