# Generated by Django 4.1.1 on 2023-03-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0002_profile_lifeline2_checked_profile_lifeline2_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline1_postcount',
            field=models.IntegerField(default=0),
        ),
    ]
