# Generated by Django 4.1.1 on 2023-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0009_easyquestion_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focuscount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifeline1_using',
            field=models.BooleanField(default=False),
        ),
    ]
