# Generated by Django 4.1.1 on 2023-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0011_profile_lifeline3_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyquestion',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timeLLUsed',
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline1_question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lifeline2_status',
            field=models.BooleanField(default=True),
        ),
    ]
