# Generated by Django 4.1.1 on 2023-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0017_end_profile_minusmrks_profile_plusmrks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='End',
        ),
        migrations.AlterField(
            model_name='profile',
            name='minusmrks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plusmrks',
            field=models.IntegerField(default=4),
        ),
    ]
