# Generated by Django 4.1.1 on 2023-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0018_delete_end_alter_profile_minusmrks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
    ]
