# Generated by Django 4.1.1 on 2023-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0019_profile_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifeline3_used',
            field=models.BooleanField(default=False),
        ),
    ]
