# Generated by Django 4.0.5 on 2023-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_RC', '0021_profile_cache_profile_cacheanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline3_status',
            field=models.BooleanField(default=False),
        ),
    ]
